### ISSUE TITLE
Run on AWS

### ISSUE THREAD

**Issue by ErnstTmp** [hardmaru/estool#2]
Hi Hardmaru,
we would be interested to run ES-Tool (Thanks for creating it!!) on a cluster of machines on AWS. Would you be interested in a pull request, if we implement this, and would it be OK for you if we use Star Cluster  (http://star.mit.edu/cluster/index.html) as a cluster management tool?

Thanks & kind regards
Ernst

**Comment by hardmaru** [comment]
Hi Ernst,

I prefer not to be tied to a particular company's cloud infrastructure. Would it be possible to write it in such a way so that it is independent of AWS or GCP (say using only the MPI framework)?

The AWS-dependent code can hopefully sit somewhere else.

If this is not possible, feel free to implement a forked implementation of the AWS cluster machine version. Would love to see how you did it in the future.

Thanks and Regards.

**Comment by MaxwellRebo** [comment]
@ErnstTmp just make a docker image or something. I agree with @hardmaru that the tool itself should remain pure, and free of specific opinions on infrastructure or tools (outside of what is needed to make it function, such as numpy).

**Comment by ErnstTmp** [comment]
Hi,
 thanks, I agree, it makes sense to make it agnostic of cloud service provider. I will use mpirun first and will create a pull request as soon as I have something.

**Comment by hardmaru** [comment]
Thanks, looking forward to seeing it work on multiple machines-
