### ISSUE TITLE
PEPG and NES

### ISSUE THREAD

**Issue by Wook133** [hardmaru/estool#27]
Looking through your implementation of PEPG, is it accurate to call it a NES?

**Comment by hardmaru** [comment]
Hi @Wook133,

Thanks for the question.

My implementation is basically Section 6 of Williams1992 [REINFORCE](https://people.cs.umass.edu/~barto/courses/cs687/williams92simple.pdf) paper, but using the extra numerical tricks and reward shaping from [Parameter-exploring Policy Gradients](http://www.jmlr.org/papers/volume15/wierstra14a/wierstra14a.pdf) (2006).

Section 6 of Williams1992 is basically described (or "reinvented, since they didn't cite Williams) in Algorithm 2 of Natural Evolution Strategies (2008 and JMLR version [2014](http://www.jmlr.org/papers/volume15/wierstra14a/wierstra14a.pdf)). The full NES uses the inverse Fisher information matrix (See Algorithm 3) that I haven't implemented. Perhaps you want to try that out to see if it helps on certain types of problems?

Hope that answers your question.

**Comment by Wook133** [comment]
Thank you for the clarity. 

It's definitely something I'll try in the future.
