### ISSUE TITLE
How to train "KukaBulletEnv-v0" ?

### ISSUE THREAD

**Issue by pyni** [hardmaru/estool#9]
I use the following order:
python train.py bullet_kuka_grasping -n 8 -t 4
I have trained kuka for a whole night, but the reward still has no change:"-1869.074175"
('improvement', 8150, -149.94043125000007, 'curr', -1869.074175, 'prev', -1719.13374375, 'best', -1719.13374375)

Then i use  the following order to do the evaluation:
python model.py bullet_kuka_grasping log/bullet_kuka_grasping.cma.1.32.json
The kuka can still not grasp the object.

![image](https://user-images.githubusercontent.com/18031767/39402612-6e1be70e-4b96-11e8-8259-1c823c56913d.png)

![image](https://user-images.githubusercontent.com/18031767/39402614-7eca6f12-4b96-11e8-95f2-e86451871eed.png)

Could you please give some advices?

**Comment by worldmodels** [comment]
Can you try:

`python train.py bullet_kuka_grasping -e 16 -n 8 -t 8`

Since the reward is sparse you want to average over 16 rollouts or so (for each episode), as described in [Evolving Stable Strategies](http://blog.otoro.net/2017/11/12/evolving-stable-strategies/).

To replicate my setup using 16 cores would be:

`python train.py bullet_kuka_grasping -e 16 -n 16 -t 16`

Although this will be a bit slow, so I think the first command will work

**Comment by hardmaru** [comment]
Can you try:

python train.py bullet_kuka_grasping -e 16 -n 8 -t 8

Since the reward is sparse you want to average over 16 rollouts or so (for each episode), as described in Evolving Stable Strategies.

To replicate my setup using 16 cores would be:

python train.py bullet_kuka_grasping -e 16 -n 16 -t 16

Although this will be a bit slow, so I think the first command will work

**Comment by hardmaru** [comment]
Can you try:

`python train.py bullet_kuka_grasping -e 16 -n 8 -t 8`

Since the reward is sparse you want to average over 16 rollouts or so (for each episode), as described in [Evolving Stable Strategies](http://blog.otoro.net/2017/11/12/evolving-stable-strategies/).

To replicate my setup using 16 cores would be:

`python train.py bullet_kuka_grasping -e 16 -n 16 -t 16`

Although this will be a bit slow, so I think the first command will work

**Comment by pyni** [comment]
Thanks!
I will try it.

**Comment by pyni** [comment]
I have tried：
python train.py bullet_kuka_grasping -e 16 -n 16 -t 16
At first, it succeeds for many times：
![image](https://user-images.githubusercontent.com/18031767/39412574-491cf2e8-4c51-11e8-9a9f-e63e24a3f1da.png)

But later, the number of success decreases a lot：
![image](https://user-images.githubusercontent.com/18031767/39412594-842d6a2a-4c51-11e8-8b9c-63e89689b070.png)

And i tried the latest iteration：
it can still not grasp the object.
![image](https://user-images.githubusercontent.com/18031767/39412639-3371fbea-4c52-11e8-9e24-58d699a2185f.png)

It seems that, the kuka will always choose the actions with least “actionCost”.

**Comment by hardmaru** [comment]
What’s your average score from your current batch? I got to around 6500-7500 range after 2 days on a 64 core machine, averaged over 16 trials per episode.

**Comment by pyni** [comment]
OK，maybe my training time is not enough. I will try again.

**Comment by pyni** [comment]
I know that it the problem for kuka.py. Thanks for your suggestions.

**Comment by hardmaru** [comment]
Great. What kind of average scores did you get in the end?
